version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 
    #  - image: mongo:3.4.4
    steps:
      - checkout 
      - run:
          name: update-npm
          command: |
              sudo npm install -g n
              sudo n stable
              pwd
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: install newman
          command: sudo npm install -g newman     
      - run:
          name: install forever
          command: sudo npm install -g forever     

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules    
      
      - run:
          name: setup connection
          command: forever start app.js
      - run: 
          name: Test
          command: newman run test.postman_collection.json
      - run:
          name: Setup aws configure file variables
          command: |
              echo "${AWS_ACCESS_KEY_ID}" >> ~/aws1.txt
              echo "${AWS_SECRET_ACCESS_KEY}" >> ~/aws1.txt
              echo "${AWS_REGION}" >> ~/aws1.txt
              echo "json" >> ~/aws1.txt
              
      - run:
          name: Install awscli
          command: |
              sudo apt-get update
              sudo apt-get install -y python-pip python-dev
              sudo pip install awscli
              aws --version
              aws configure < ~/aws1.txt
              echo "${AWS_ACCESS_KEY_ID}"
      - run:
          name: Checking application
          command: aws deploy get-application --application-name CodeDeployGitHubDemo-App
      - run:
          name: Checking Deployment Config
          command: aws deploy get-deployment-config --deployment-config-name CodeDeployDefault.AllAtOnce
      - run:
          name: Checking Deployment Group
          command: aws deploy get-deployment-group --application-name CodeDeployGitHubDemo-App --deployment-group-name CodeDeployGitHubDemo-DepGrp     
      - run:
          name: Compressing Source Contents
          command: cd "/home/circleci/project" && zip -rq "/tmp/first.zip" .
      - run:
          name: Copying bundle to S3
          command: aws s3 cp --sse AES256 "/tmp/first.zip" "s3://todolist-bucket-demo/first.zip"
      # - run:
      #     name: Limiting Deploy Revisions per Bucket/Key
      #     command: |
      #         aws s3 ls "s3://todolist-bucket-demo"
      #         aws s3 rm "s3://todolist-bucket-demo/first.zip"
      - run:
          name: Registering Revision 
          command: aws deploy register-application-revision --application-name "CodeDeployGitHubDemo-App" --s3-location bucket=todolist-bucket-demo,bundleType=zip,key=first.zip --description "master first"
      - run:
          name: Creating Deployment
          command: aws deploy create-deployment --application-name CodeDeployGitHubDemo-App --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name CodeDeployGitHubDemo-DepGrp --s3-location bucket=todolist-bucket-demo,bundleType=zip,key=first.zip --description "Deployed via CircleCI"
      # - run:
      #     name: Deployment to S3 bucket
      #     command: aws s3 sync . s3://todolist-bucket-demo --delete      



      # - run:
      #     name: CodeDeploy
      #     command: |
      #         echo 'export COMMIT_ID=$(git rev-parse HEAD)' >>$BASH_ENV
      #         echo $COMMIT_ID
      

  # test:
  #   docker:
  #     - image: circleci/node:4.8.2
  #   steps:
  #     - checkout
  #     - run:
  #         name: update-npm
  #         command: |
  #             sudo npm install -g n
  #             sudo n stable
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: install-npm-wee
  #         command: npm install
  #     # - run:
  #     #     name: install newman
  #     #     command: npm install -g newman     
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #         paths:
  #           - ./node_modules    
      
  #     - run:
  #         name: test
  #         command: node app
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests


 #     - run:
  #         name: test
  #         command: npm test

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build



