version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 
    #  - image: mongo:3.4.4
    steps:
      - checkout 
      - run:
          name: update-npm
          command: |
              sudo npm install -g n
              sudo n stable
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      # - run:
      #     name: install newman
      #     command: npm install -g newman     
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules    
      - run:
          name: start connection and test
          command: |
              set -e
              node app
      - run:
          name: Setup aws configure file variables
          command: |
              echo "${AWS_ACCESS_KEY_ID}" >> ~/aws1.txt
              echo "${AWS_SECRET_ACCESS_KEY}" >> ~/aws1.txt
              echo "${AWS_REGION}" >> ~/aws1.txt
              echo "json" >> ~/aws1.txt
              
      - run:
          name: Install awscli
          command: |
              sudo apt-get update
              sudo apt-get install -y python-pip python-dev
              sudo pip install awscli
              aws --version
              aws configure < ~/aws1.txt
              echo "${AWS_ACCESS_KEY_ID}"
      - run:
          name: Checking application
          command: aws deploy get-application --application-name CodeDeployGitHubDemo-App
      - run:
          name: Checking Deployment Config
          command: aws deploy get-deployment-config --deployment-config-name CodeDeployDefault.AllAtOnce
      - run:
          name: Checking Deployment Group
          command: aws deploy get-deployment-group --application-name CodeDeployGitHubDemo-App --deployment-group-name CodeDeployGitHubDemo-DepGrp     
      



      # - run:
      #     name: CodeDeploy
      #     command: |
      #         echo 'export COMMIT_ID=$(git rev-parse HEAD)' >>$BASH_ENV
      #         echo $COMMIT_ID
      

  # test:
  #   docker:
  #     - image: circleci/node:4.8.2
  #   steps:
  #     - checkout
  #     - run:
  #         name: update-npm
  #         command: |
  #             sudo npm install -g n
  #             sudo n stable
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: install-npm-wee
  #         command: npm install
  #     # - run:
  #     #     name: install newman
  #     #     command: npm install -g newman     
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #         paths:
  #           - ./node_modules    
      
  #     - run:
  #         name: test
  #         command: node app
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests


 #     - run:
  #         name: test
  #         command: npm test

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build



