version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 
    #  - image: mongo:3.4.4
    steps:
      - checkout 
      - run:
          name: update-npm
          command: |
              sudo npm install -g n
              sudo n stable
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      # - run:
      #     name: install newman
      #     command: npm install -g newman     
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules    
      # - run:
      #     name: Install awscli
      #     command: |
      #         sudo apt-get update
      #         sudo apt-get install -y python-pip python-dev
      #         sudo pip install awscli
      #         aws --version
      #         aws configure < aws.txt
      #         echo "${AWS_ACCESS_KEY_ID}"
      # - run:
      #     name: CodeDeploy
      #     command: |
      #         echo 'export COMMIT_ID=$(git rev-parse HEAD)' >>$BASH_ENV
      #         echo $COMMIT_ID
      

      # - run:
      #     name: start connection and test
      #     command: node app
  test:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
        name: test
        command: node app



           

  # two:
  #   docker:
  #     - image: circleci/node:4.8.2
  #     - image: mongo:3.4.4
  #   steps:
  #     - checkout
  #     - run:
  #         name: update-npm
  #         command: 'sudo npm install -g npm@5'
  #     - restore_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #     - run:
  #         name: install-npm-wee
  #         command: npm install
  #     - save_cache:
  #         key: dependency-cache-{{ checksum "package.json" }}
  #         paths:
  #           - ./node_modules      
      
  #     - run:
  #         name: test
  #         command: npm test

# workflows:
#   version: 2
#   one_and_two:
#     jobs:
#       - build
#       - test


